### ISSUE TITLE
Créer une communauté de collège utilisateur

### ISSUE THREAD

**Issue by Flightan** [sgmap/bourses#11]
Si un agent à un problème:
 - il peut lister les collège près de lui (dans le département)
 - voir le fil de discussion de bourse sur le forum des gestionnaires (http://gestionnaires.actifforum.com/t34300-eboursesco-dematerialisez-les-demandes-de-bourses-de-college)

**Comment by Pierre2Maulmont** [comment]
Et compter les utilisateurs du département, pour stimuler la communauté locale

**Comment by Flightan** [comment]
Ecran Ma campagne 

Campagne ouverte / fermée
Aide à la cantine
Stats

Ecran Aide
FAQ
Les établissements dans mon département (avec contact)
Notre adresse mail
Post sur le forum

Gestion des ribs

<img width="283" alt="screen shot 2016-07-20 at 11 58 39" src="https://cloud.githubusercontent.com/assets/1475946/16982732/ccb1f75a-4e71-11e6-8701-599235ee02f7.png">
